plugins {
    id "com.android.application"
}

configurations.configureEach {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == "org.jetbrains.kotlin" && details.requested.name.startsWith("kotlin-stdlib")) {
            details.useVersion "1.9.24"
        }
    }
}

android {
    namespace "com.intelafri.omttracker"
    compileSdk 35

    defaultConfig {
        applicationId "com.intelafri.omttracker"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.core:core:1.15.0"
}
